### PR TITLE
fix: set the page language on the html element

### PR DESCRIPTION
**Pull request by eatyourgreens**
Add a custom `pages/_document.tsx` and set the default language to `en-GB`.

See [WCAG 2 Success Criterion 3.1.1: Language of page](https://www.w3.org/WAI/WCAG22/Understanding/language-of-page.html).

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Adding a custom document seems like overkill just to make sure the page language is set in the HTML, but I don’t think you can set it as an option in `next.config.js`.

**Comment by eatyourgreens** [comment]
I might be wrong. If we set up the default [i18n config](https://nextjs.org/docs/pages/building-your-application/routing/internationalization) in `next.config.js`, that should add a default page language, without needing to create a custom document.

**Comment by alasdairwilson** [comment]
> I might be wrong. If we set up the default [i18n config](https://nextjs.org/docs/pages/building-your-application/routing/internationalization) in `next.config.js`, that should add a default page language, without needing to create a custom document.

I think you are right, I don't really know if there is a benefit versus what you've done here? I doubt we have plans to support other locales, even in the extremely long term.

**Comment by eatyourgreens** [comment]
I think `next.config.js` might be easier to maintain. I've switched this PR over to using the `i18n` config with a single default locale, which works when I run it locally.

**Comment by eatyourgreens** [comment]
Oh wait, you can't use `i18n` config with static builds. Custom document it is, then, I suppose.

**Comment by eatyourgreens** [comment]
Rebased this onto the latest main branch. Should be good to go now.

**Comment by alasdairwilson** [comment]
> Oh wait, you can't use `i18n` config with static builds. Custom document it is, then, I suppose.

https://locize.com/blog/next-app-dir-i18n/

Looks like this is the way to go HOWEVER since we are not actually supporting multiple localisations then this is totally pointless and we should use your hardcoded solution :thumbs:

Thanks @eatyourgreens

**Review by alasdairwilson — APPROVED** [review]
lgtm 👍

**Pull request merged**
